apiVersion: v1
kind: Namespace
metadata:
  name: seattle
spec:
  finalizers:
  - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mes
  namespace: seattle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mes
  template:
    metadata:
      labels:
        app: mes
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: mes
        image: docker.io/tejas7719/ontologies_dbg:0.0.2
        env:
        - name: StationType
          value: "MES"
        - name: ProductionLineName
          value: "seattle"
        - name: STORAGE_CONNECTION_STRING
          value: "[mystorageaccountkey1connectionstring]"
        - name: STORAGE_CONTAINER_NAME
          value: "seattle"
